### Register
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "email": "test@example.com",
    "password": "password123",
    "name":"xxxx"
}

### Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "test@example.com",
    "password": "password123"
}


### Refresh
POST {{baseUrl}}/auth/refresh
Content-Type: application/json

{ }


### Logout
POST {{baseUrl}}/auth/refresh
Content-Type: application/json

{ }

